/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as HowtoRouteImport } from './routes/howto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as AccountBillingRouteImport } from './routes/account_.billing'
import { Route as AccountBuildsRouteImport } from './routes/account_.builds'
import { Route as AccountLicensesRouteImport } from './routes/account_.licenses'
import { Route as AccountProductsRouteImport } from './routes/account_.products'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const HowtoRoute = HowtoRouteImport.update({
  id: '/howto',
  path: '/howto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account_/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBuildsRoute = AccountBuildsRouteImport.update({
  id: '/account_/builds',
  path: '/account/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLicensesRoute = AccountLicensesRouteImport.update({
  id: '/account_/licenses',
  path: '/account/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProductsRoute = AccountProductsRouteImport.update({
  id: '/account_/products',
  path: '/account/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/generate': typeof GenerateRoute
  '/howto': typeof HowtoRoute
  '/login': typeof LoginRoute
  '/presets': typeof PresetsRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/skins': typeof SkinsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/technology': typeof TechnologyRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/builds': typeof AccountBuildsRoute
  '/account/licenses': typeof AccountLicensesRoute
  '/account/products': typeof AccountProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/generate': typeof GenerateRoute
  '/howto': typeof HowtoRoute
  '/login': typeof LoginRoute
  '/presets': typeof PresetsRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/skins': typeof SkinsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/technology': typeof TechnologyRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/builds': typeof AccountBuildsRoute
  '/account/licenses': typeof AccountLicensesRoute
  '/account/products': typeof AccountProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/generate': typeof GenerateRoute
  '/howto': typeof HowtoRoute
  '/login': typeof LoginRoute
  '/presets': typeof PresetsRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/skins': typeof SkinsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/technology': typeof TechnologyRoute
  '/account_/billing': typeof AccountBillingRoute
  '/account_/builds': typeof AccountBuildsRoute
  '/account_/licenses': typeof AccountLicensesRoute
  '/account_/products': typeof AccountProductsRoute
  '/products_/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/generate'
    | '/howto'
    | '/login'
    | '/presets'
    | '/pricing'
    | '/products'
    | '/skins'
    | '/status'
    | '/support'
    | '/technology'
    | '/account/billing'
    | '/account/builds'
    | '/account/licenses'
    | '/account/products'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/generate'
    | '/howto'
    | '/login'
    | '/presets'
    | '/pricing'
    | '/products'
    | '/skins'
    | '/status'
    | '/support'
    | '/technology'
    | '/account/billing'
    | '/account/builds'
    | '/account/licenses'
    | '/account/products'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/generate'
    | '/howto'
    | '/login'
    | '/presets'
    | '/pricing'
    | '/products'
    | '/skins'
    | '/status'
    | '/support'
    | '/technology'
    | '/account_/billing'
    | '/account_/builds'
    | '/account_/licenses'
    | '/account_/products'
    | '/products_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  GenerateRoute: typeof GenerateRoute
  HowtoRoute: typeof HowtoRoute
  LoginRoute: typeof LoginRoute
  PresetsRoute: typeof PresetsRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  SkinsRoute: typeof SkinsRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  TechnologyRoute: typeof TechnologyRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountBuildsRoute: typeof AccountBuildsRoute
  AccountLicensesRoute: typeof AccountLicensesRoute
  AccountProductsRoute: typeof AccountProductsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howto': {
      id: '/howto'
      path: '/howto'
      fullPath: '/howto'
      preLoaderRoute: typeof HowtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/billing': {
      id: '/account_/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/builds': {
      id: '/account_/builds'
      path: '/account/builds'
      fullPath: '/account/builds'
      preLoaderRoute: typeof AccountBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/licenses': {
      id: '/account_/licenses'
      path: '/account/licenses'
      fullPath: '/account/licenses'
      preLoaderRoute: typeof AccountLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/products': {
      id: '/account_/products'
      path: '/account/products'
      fullPath: '/account/products'
      preLoaderRoute: typeof AccountProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  GenerateRoute: GenerateRoute,
  HowtoRoute: HowtoRoute,
  LoginRoute: LoginRoute,
  PresetsRoute: PresetsRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  SkinsRoute: SkinsRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  TechnologyRoute: TechnologyRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountBuildsRoute: AccountBuildsRoute,
  AccountLicensesRoute: AccountLicensesRoute,
  AccountProductsRoute: AccountProductsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
